project:
  type: website
  output-dir: _site

website:
  title: "CasCrab"
  description: "About CasCrab"
  site-url: "https://cascrab.github.io/"
  navbar:
    left:
      - text: About
        href: index.qmd
    right:
      - text: GitHub
        href: https://github.com/CasCrab
  page-footer: |
    &copy; 2026 CasCrab. All rights reserved.

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    date-format: "MMM D, YYYY [at] h:mm a"
    toc: true
    code-fold: true
    code-copy: true
    anchor-sections: true
    author: "CasCrab"
    comments:
      utterances:
        repo: CasCrab/CasCrab.github.io
        issue-term: pathname
        label: "comment"
        theme: "github-light"

filters:
  - quarto
